name: Publish package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@master
        with:
          version: 12
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm i --production
      
      - name: Build
        run: npm run build

      - uses: shawnbot/npm-publish-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NOTE: use the NODE_ prefix instead of NPM_ here!
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
